In [ ]:
'''
anaconda prompt 실행

# tf라는 이름의 가상환경 생성, python 버젼 3.6 기준
conda create -n tf python=3.6
# 가상환경 tf 활성화, base->tf
conda activate tf

# 라이브러리 설치
conda install python=3.6
pip install tensorflow
conda install pandas
conda install matplotlib
conda install scikit-learn
conda install keras
conda install jupyter notebook

# 재실행
conda activate tf
jupyter notebook # jupyter notebook 실행
'''

In [1]:
# 라이브러리 불러오기
import tensorflow as tf
import keras
import numpy as np

In [17]:
# 배열 array 생성
array = np.array([[1,2,3], [4,5,6,], [7,8,9], [10,11,12]])
print('array =', array)

print('\n')
print('요소의 자료형:', array.dtype) # 수치형 자료
print('요소 수:', array.size)        # 1, 2, 3, ..., 12; 12개
print('차원 수:', array.ndim)        # list 안에 list
print('각 차원의 요소 수:', array.shape) # list가 4개, list 안에 3개

array = [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


요소의 자료형: int32
요소 수: 12
차원 수: 2
각 차원의 요소 수: (4, 3)


In [14]:
array2 = np.array('a')
print('array2 =', array2)

print('\n')
print('요소의 자료형:', array2.dtype) # 수치형 자료
print('요소 수:', array2.size)        # 'a' 1개
print('차원 수:', array2.ndim)        # list 없고 단순히 문자 한개
print('각 차원의 요소 수:', array2.shape)

array2 = a


요소의 자료형: <U1
요소 수: 1
차원 수: 0
각 차원의 요소 수: ()


In [15]:
array3 = np.array([1,2,3])
print('array3 =', array3)

print('\n')
print('요소의 자료형:', array3.dtype) # 수치형 자료
print('요소 수:', array3.size)        # 1, 2, 3; 3개
print('차원 수:', array3.ndim)        # list 1개
print('각 차원의 요소 수:', array3.shape) # list 안에 3개 요소

array3 = [1 2 3]


요소의 자료형: int32
요소 수: 3
차원 수: 1
각 차원의 요소 수: (3,)


In [20]:
# 배열의 모든 요소를 2로 나눔
div_array_1 = array / 2
print('div_array_1 = ', div_array_1)


print('\n')
# array의 [0][0]번째 요소(1)를 2로 나누고 결과 출력
div_array_2 = array[0][0] / 2
print('div_array_2 = ', div_array_2)


print('\n')
# array의 [3][2]번째 요소(12)를 2로 나누고 결과 출력
div_array_3 = array[3][2] / 2
print('div_array_3 = ', div_array_3)

div_array_1 =  [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [5.  5.5 6. ]]


div_array_2 =  0.5


div_array_3 =  6.0
