In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tf 구버젼 사용
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [6]:
X = tf.constant([[1., 2.], [5., 6.]])

Y1 = tf.reduce_mean(X)
Y2 = tf.reduce_mean(X, axis = 0)
Y3 = tf.reduce_mean(X, axis = 1)

sess = tf.Session()

print('X = ', sess.run(X))
print('Y1(axis no) = ', sess.run(Y1)) # 전체 평균 (1+2+5+6)/4
print('Y2(axis 0) = ', sess.run(Y2))  # 세로로 평균
print('Y3(axis 1) = ', sess.run(Y3))  # 가로로 평균

X =  [[1. 2.]
 [5. 6.]]
Y1(axis no) =  3.5
Y2(axis 0) =  [3. 4.]
Y3(axis 1) =  [1.5 5.5]


In [7]:
arr = np.arange(0, 32) # 0부터 31까지
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [18]:
v = arr.reshape(4, 2, 4) # 4x2 행렬을 4개
v
# row1, 0~7; row2, 8~15
# col1, 0~4; col2, 4~7
# depth; row, col 정해진 뒤 좌->우 번호

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [21]:
v[1] # row2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
v[0,1] # row1, col2

array([4, 5, 6, 7])

In [23]:
v[3,1,1] # row4, col2, depth2

29

In [24]:
v.ndim

3

In [25]:
v.sum()

496

In [29]:
res01 = v.sum(axis = 0) # axis=0은 세로로, axis=1은 가로로
res01.shape # 2x4

(2, 4)

In [30]:
res01

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [34]:
res02 = v.sum(axis = 1)
res02.shape # 4x4

(4, 4)

In [ ]:
res02

In [35]:
res03 = v.sum(axis = 2)
res03.shape # 4x2

(4, 2)

In [36]:
res03

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118]])