In [34]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tf 구버젼 사용

In [2]:
# hypothesis = X * W + b

X = tf.placeholder(tf.float32, [None, 3])
x_data = [[1, 2, 3], [4, 5, 6]]
W = tf.Variable(tf.random_normal([3, 2])) # 3x2, 성분은 랜덤
b = tf.Variable(tf.random_normal([2, 1])) # 2x1, 성분은 랜덤
hypothesis = tf.matmul(X, W) + b

sess = tf.Session()
sess.run(tf.global_variables_initializer())


print('=== x_data ===')
print(x_data)
print('=== W ===')
print(sess.run(W))
print('=== b ===')
print(sess.run(b))

print('=== hypothesis ===')
print(sess.run(hypothesis, feed_dict = {X: x_data}))
sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-1.2296703   0.40549922]
 [-1.0980173   0.40742126]
 [-0.03308927 -1.1595898 ]]
=== b ===
[[0.35814393]
 [1.3888451 ]]
=== hypothesis ===
[[-3.1668286 -1.9002837]
 [-9.218458  -1.9095904]]


In [ ]:
## gradient descent

In [49]:
# 방법1
x_data = [1, 2, 3]
y_data = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), name = 'weight')
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

y_hat = X * W

cost = tf.reduce_mean(tf.square(y_hat - Y))

learning_rate = 0.1
gradient = tf.reduce_mean((W * X - Y) * X)
descent = W - learning_rate * gradient
update = W.assign(descent)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(30):
    sess.run(update, feed_dict = {X: x_data, Y: y_data})
    print(step, sess.run(cost, feed_dict = {X: x_data, Y: y_data}), sess.run(W))

0 2.9357643 [0.2068466]
1 0.8350617 [0.5769849]
2 0.2375286 [0.77439195]
3 0.067563705 [0.8796757]
4 0.019218136 [0.935827]
5 0.005466497 [0.9657744]
6 0.0015549114 [0.9817464]
7 0.0004422859 [0.9902647]
8 0.00012580525 [0.99480784]
9 3.578514e-05 [0.9972308]
10 1.017922e-05 [0.9985231]
11 2.895258e-06 [0.9992123]
12 8.235667e-07 [0.9995799]
13 2.3424059e-07 [0.99977595]
14 6.666357e-08 [0.9998805]
15 1.895381e-08 [0.9999363]
16 5.3947296e-09 [0.999966]
17 1.5321954e-09 [0.9999819]
18 4.3741485e-10 [0.99999034]
19 1.2140333e-10 [0.9999949]
20 3.44329e-11 [0.99999726]
21 1.05409015e-11 [0.9999985]
22 2.8954616e-12 [0.9999992]
23 7.6383344e-13 [0.9999996]
24 2.6526928e-13 [0.99999976]
25 9.947598e-14 [0.9999999]
26 2.4868996e-14 [0.99999994]
27 0.0 [1.]
28 0.0 [1.]
29 0.0 [1.]


In [18]:
# 방법2
x_data = [1,2,3]
y_data = [1,2,3]

W = tf.Variable(tf.random_normal([1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

y_hat = x_data * W + b

# cost function
cost = tf.reduce_mean(tf.square(y_hat - y_data))

# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(1000):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b))

0 0.30018649 [0.65630597] [1.157958]
20 0.065213315 [0.70340484] [0.6742305]
40 0.024639333 [0.81769] [0.41443354]
60 0.009309411 [0.8879384] [0.2547424]
80 0.003517349 [0.93111837] [0.15658414]
100 0.0013289503 [0.9576601] [0.09624856]
120 0.00050211354 [0.97397465] [0.05916174]
140 0.00018971182 [0.9840028] [0.03636533]
160 7.167804e-05 [0.9901669] [0.02235286]
180 2.7081862e-05 [0.99395585] [0.01373977]
200 1.0232455e-05 [0.99628484] [0.00844552]
220 3.8661015e-06 [0.99771637] [0.00519127]
240 1.4605876e-06 [0.9985963] [0.00319092]
260 5.518984e-07 [0.99913716] [0.00196141]
280 2.0854941e-07 [0.99946964] [0.00120562]
300 7.879633e-08 [0.999674] [0.0007411]
320 2.9778057e-08 [0.9997996] [0.00045551]
340 1.1252598e-08 [0.99987686] [0.00027999]
360 4.2427737e-09 [0.9999243] [0.00017206]
380 1.6070557e-09 [0.99995345] [0.00010579]
400 6.066071e-10 [0.9999714] [6.5024964e-05]
420 2.2900944e-10 [0.9999824] [4.0003903e-05]
440 8.6949864e-11 [0.9999892] [2.4584515e-05]
460 3.2528678e-11 [0.

In [21]:
# placeholder 이용
W = tf.Variable(tf.random_normal([1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

x = tf.placeholder(tf.float32, shape = [None])
Y = tf.placeholder(tf.float32, shape = [None])

y_hat = x * W + b

cost = tf.reduce_mean(tf.square(y_hat - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train],
                                        feed_dict = {x: [1,2,3,4,5], Y: [2.1,3.1,4.1,5.1,6.1]})
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)

0 3.5247002 [0.6114703] [0.94185346]
20 0.00042436743 [1.0103338] [1.0556415]
40 0.00030781268 [1.0113436] [1.0590137]
60 0.00026880874 [1.0106083] [1.0617001]
80 0.0002347542 [1.0099136] [1.0642086]
100 0.00020501052 [1.0092643] [1.0665526]
120 0.00017903425 [1.0086576] [1.0687432]
140 0.0001563503 [1.0080905] [1.0707905]
160 0.00013654347 [1.0075606] [1.0727035]
180 0.00011924489 [1.0070655] [1.0744911]
200 0.00010413644 [1.0066028] [1.0761617]
220 9.09411e-05 [1.0061704] [1.077723]
240 7.942077e-05 [1.0057663] [1.0791818]
260 6.935983e-05 [1.0053887] [1.0805452]
280 6.057244e-05 [1.0050359] [1.0818192]
300 5.2898948e-05 [1.004706] [1.0830097]
320 4.619697e-05 [1.0043977] [1.0841224]
340 4.0344537e-05 [1.0041099] [1.0851622]
360 3.523344e-05 [1.0038407] [1.086134]
380 3.0768442e-05 [1.0035892] [1.0870421]
400 2.6872363e-05 [1.0033541] [1.0878906]
420 2.34671e-05 [1.0031344] [1.0886836]
440 2.0495285e-05 [1.0029292] [1.0894246]
460 1.7898277e-05 [1.0027373] [1.0901172]
480 1.5630523e-

In [ ]:
## 파이프 부식도 문제

In [50]:
# 방법1
x1_data = [7.93, 8.07, 7.85, 7.98, 7.77, 7.87] # ph
x2_data = [11.9, 12.9, 11, 9.3, 6.4, 12.9]     # 탁도
x3_data = [19, 26.6, 17, 15.3, 13.1, 11.9]     # 염소량
x4_data = [59.8, 59.6, 26.3, 27.4, 51.5, 41.9] # 약품농도
y_data = [2.2, 10.3, 19.5, 13.2, 7.2, 23.5]    # 부식도

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
x4 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
w4 = tf.Variable(tf.random_normal([1]), name = 'weight4')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

y_hat = x1*w1 + x2*w2 + x3*w3 + x4*w4 + b

cost = tf.reduce_mean(tf.square(y_hat - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10000):
    cost_val, w1_val, w2_val, w3_val, w4_val, b_val, _ = sess.run([cost, w1, w2, w3, w4, b, train],
                                   feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, x4: x4_data, Y: y_data})
    if step % 100 == 0:
        print("Step: ", step, "\n", "Cost: ", cost_val, "\n", "weight:\n", w1_val, w2_val, w3_val, w4_val, b_val, "\n")


Step:  0 
 Cost:  3303.6692 
 weight:
 [-0.04182439] [0.32016504] [-0.24513641] [1.3960097] [0.70959765] 

Step:  100 
 Cost:  120.5842 
 weight:
 [-0.15735625] [0.17048702] [-0.5383231] [0.41459593] [0.69502485] 

Step:  200 
 Cost:  111.18075 
 weight:
 [-0.12062194] [0.22959833] [-0.48750657] [0.37098178] [0.6996815] 

Step:  300 
 Cost:  102.83672 
 weight:
 [-0.08470777] [0.28693062] [-0.43890762] [0.33389717] [0.7042385] 

Step:  400 
 Cost:  95.37553 
 weight:
 [-0.05022704] [0.34167728] [-0.39386636] [0.2989844] [0.7086177] 

Step:  500 
 Cost:  88.69851 
 weight:
 [-0.01710613] [0.39397463] [-0.3521718] [0.26609853] [0.7128286] 

Step:  600 
 Cost:  82.71813 
 weight:
 [0.01472739] [0.44395563] [-0.31361866] [0.2351209] [0.7168797] 

Step:  700 
 Cost:  77.35678 
 weight:
 [0.04534177] [0.49174514] [-0.2780135] [0.20593987] [0.7207797] 

Step:  800 
 Cost:  72.54565 
 weight:
 [0.07480137] [0.537461] [-0.24517485] [0.17845047] [0.7245365] 

Step:  900 
 Cost:  68.22372 
 weigh

Step:  7900 
 Cost:  19.113272 
 weight:
 [0.98569936] [1.7159927] [-0.16696943] [-0.26968354] [0.84353197] 

Step:  8000 
 Cost:  19.009638 
 weight:
 [0.9921009] [1.7219648] [-0.172063] [-0.27021074] [0.8443904] 

Step:  8100 
 Cost:  18.908659 
 weight:
 [0.99842894] [1.7278293] [-0.17711754] [-0.27071574] [0.8452394] 

Step:  8200 
 Cost:  18.810247 
 weight:
 [1.004685] [1.7335882] [-0.18213211] [-0.2711998] [0.8460785] 

Step:  8300 
 Cost:  18.714333 
 weight:
 [1.0108705] [1.7392445] [-0.1871056] [-0.27166405] [0.84690917] 

Step:  8400 
 Cost:  18.620855 
 weight:
 [1.0169868] [1.7447996] [-0.1920371] [-0.2721095] [0.84772986] 

Step:  8500 
 Cost:  18.529732 
 weight:
 [1.0230355] [1.7502567] [-0.19692579] [-0.2725373] [0.8485426] 

Step:  8600 
 Cost:  18.440895 
 weight:
 [1.0290171] [1.7556173] [-0.20177093] [-0.2729483] [0.84934574] 

Step:  8700 
 Cost:  18.354311 
 weight:
 [1.0349337] [1.7608835] [-0.20657192] [-0.27334347] [0.850141] 

Step:  8800 
 Cost:  18.269882 


In [33]:
# 방법2

x_data = [[7.93,11.9, 19.0, 59.8], [8.07,12.9,26.6,59.6], [7.85,11.0,17.0,26.3], [7.98,9.3,15.3,27.4], [7.77,6.4,13.1,51.5], [7.87,12.9,11.9,41.9]]    
y_data = [[2.2], [10.3], [19.5], [13.2], [7.2], [23.5]]

X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

y_hat = tf.matmul(X, W) + b

# cost function
cost = tf.reduce_mean(tf.square(y_hat - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10000):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print("Step: ", step, "\n", "Cost: ", cost_val, "\n", "weight:\n", W_val, b_val, "\n")


Step:  0 
 Cost:  227.96684 
 weight:
 [[-0.13825478]
 [ 0.40195566]
 [-1.032026  ]
 [ 0.7260343 ]] [0.04676725] 

Step:  100 
 Cost:  140.32405 
 weight:
 [[-0.12022272]
 [ 0.43648165]
 [-1.0121688 ]
 [ 0.533604  ]] [0.04903231] 

Step:  200 
 Cost:  127.846214 
 weight:
 [[-0.08058939]
 [ 0.49992463]
 [-0.94416016]
 [ 0.48652646]] [0.05402982] 

Step:  300 
 Cost:  116.74524 
 weight:
 [[-0.04258551]
 [ 0.5603711 ]
 [-0.8804833 ]
 [ 0.4427978 ]] [0.05882628] 

Step:  400 
 Cost:  106.86441 
 weight:
 [[-0.00622132]
 [ 0.6178516 ]
 [-0.821103  ]
 [ 0.40161675]] [0.06342012] 

Step:  500 
 Cost:  98.065956 
 weight:
 [[ 0.02859276]
 [ 0.67253023]
 [-0.7657606 ]
 [ 0.36283112]] [0.06782231] 

Step:  600 
 Cost:  90.22791 
 weight:
 [[ 0.06194163]
 [ 0.72456264]
 [-0.7142123 ]
 [ 0.32630095]] [0.07204334] 

Step:  700 
 Cost:  83.242065 
 weight:
 [[ 0.0939053 ]
 [ 0.7740954 ]
 [-0.6662286 ]
 [ 0.29189435]] [0.07609303] 

Step:  800 
 Cost:  77.01248 
 weight:
 [[ 0.12455904]
 [ 0.821267

Step:  7500 
 Cost:  18.414186 
 weight:
 [[ 0.9860982 ]
 [ 1.8802648 ]
 [-0.24830788]
 [-0.26312792]] [0.19199404] 

Step:  7600 
 Cost:  18.336527 
 weight:
 [[ 0.9923393 ]
 [ 1.8850458 ]
 [-0.2521333 ]
 [-0.26383054]] [0.19283046] 

Step:  7700 
 Cost:  18.260866 
 weight:
 [[ 0.99850863]
 [ 1.8897232 ]
 [-0.25595042]
 [-0.26450086]] [0.19365758] 

Step:  7800 
 Cost:  18.18714 
 weight:
 [[ 1.0046078 ]
 [ 1.8942999 ]
 [-0.25975713]
 [-0.26514047]] [0.19447558] 

Step:  7900 
 Cost:  18.115278 
 weight:
 [[ 1.0106384 ]
 [ 1.8987787 ]
 [-0.26355106]
 [-0.2657512 ]] [0.19528466] 

Step:  8000 
 Cost:  18.045214 
 weight:
 [[ 1.0166024 ]
 [ 1.9031621 ]
 [-0.2673302 ]
 [-0.26633477]] [0.19608507] 

Step:  8100 
 Cost:  17.976904 
 weight:
 [[ 1.0225002]
 [ 1.9074532]
 [-0.2710927]
 [-0.2668926]] [0.19687696] 

Step:  8200 
 Cost:  17.910286 
 weight:
 [[ 1.0283344 ]
 [ 1.911654  ]
 [-0.2748368 ]
 [-0.26742607]] [0.19766049] 

Step:  8300 
 Cost:  17.845308 
 weight:
 [[ 1.034106  ]
 [ 1

In [46]:
# 방법3, csv 불러오기
import numpy as np

z = np.loadtxt('corrosion1.csv', delimiter = ',', skiprows = 1, dtype = np.float32)
x_data = z[:, 0:-1]
y_data = z[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

y_hat = tf.matmul(X, W) + b


cost = tf.reduce_mean(tf.square(y_hat - Y))

# Minimization
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())


for step in range(5000):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], 
                                   feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print("Step: ", step, "\n", "Cost: ", cost_val, "\n", "weight:\n", W_val, b_val, "\n")

Step:  0 
 Cost:  1103.9745 
 weight:
 [[-0.37565637]
 [-0.86411613]
 [ 0.3502422 ]
 [ 0.80592555]] [-1.0382992] 

Step:  100 
 Cost:  176.10426 
 weight:
 [[-0.3826397 ]
 [-0.8301607 ]
 [ 0.28815907]
 [ 0.30308113]] [-1.0392898] 

Step:  200 
 Cost:  159.65948 
 weight:
 [[-0.3312478 ]
 [-0.73409617]
 [ 0.329058  ]
 [ 0.2543037 ]] [-1.032783] 

Step:  300 
 Cost:  148.87332 
 weight:
 [[-0.28009358]
 [-0.64864707]
 [ 0.33265224]
 [ 0.22715977]] [-1.0262704] 

Step:  400 
 Cost:  139.61314 
 weight:
 [[-0.2300826 ]
 [-0.5695797 ]
 [ 0.322658  ]
 [ 0.20846355]] [-1.0198864] 

Step:  500 
 Cost:  131.22624 
 weight:
 [[-0.18150209]
 [-0.49516895]
 [ 0.3080587 ]
 [ 0.1933041 ]] [-1.0136751] 

Step:  600 
 Cost:  123.56237 
 weight:
 [[-0.13441956]
 [-0.42466027]
 [ 0.2922261 ]
 [ 0.1798102 ]] [-1.0076482] 

Step:  700 
 Cost:  116.548065 
 weight:
 [[-0.08882183]
 [-0.35767093]
 [ 0.27641112]
 [ 0.16726029]] [-1.0018048] 

Step:  800 
 Cost:  110.12536 
 weight:
 [[-0.04466669]
 [-0.29396

In [47]:
# 임의값으로 테스트
print('the actual value = 2.6, the predicted value=', sess.run(y_hat, feed_dict={X: [[7.84,13.4,24.9,72.1]]}))

the actual value = 2.6, the predicted value= [[11.209543]]


In [ ]:
## sales prediction

In [52]:
# 방법1

# data
x1_data = [4,8,9,8,8,12,6,10,6,9]
x2_data = [4,10,8,5,10,15,8,13,5,12]
y_data = [9,20,22,15,17,30,18,25,10,20]

# placeholder
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# weight, bias
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# hypothesis function
y_hat = x1*w1 + x2*w2 + b

# cost function
cost = tf.reduce_mean(tf.square(y_hat - Y))

# minimization
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-4)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10000):
    cost_val, w1_val, w2_val, b_val, _ = sess.run([cost, w1, w2, b, train],
                                                 feed_dict = {x1: x1_data, x2: x2_data, Y: y_data})
    if step % 100 == 0:
        print("Step: ", step, '\nCost: ', cost_val, '\nweight:\n', w1_val, w2_val, b_val, '\n')

# w1 = 1.678, w2 = 0.774, b = -1.896

Step:  0 
Cost:  958.2127 
weight:
 [-1.4988927] [0.46569648] [-2.5699992]
Step:  100 
Cost:  13.406511 
weight:
 [0.01774594] [2.1270666] [-2.388081]
Step:  200 
Cost:  11.55176 
weight:
 [0.1256602] [2.1452987] [-2.3692062]
Step:  300 
Cost:  11.072842 
weight:
 [0.17879331] [2.1028616] [-2.3568134]
Step:  400 
Cost:  10.62498 
weight:
 [0.22832681] [2.059474] [-2.3449812]
Step:  500 
Cost:  10.204472 
weight:
 [0.27624178] [2.017349] [-2.3334758]
Step:  600 
Cost:  9.809646 
weight:
 [0.32265857] [1.9765304] [-2.3222785]
Step:  700 
Cost:  9.438941 
weight:
 [0.36762628] [1.9369812] [-2.31138]
Step:  800 
Cost:  9.090869 
weight:
 [0.41119003] [1.8986611] [-2.3007708]
Step:  900 
Cost:  8.764046 
weight:
 [0.4533944] [1.8615317] [-2.2904418]
Step:  1000 
Cost:  8.457189 
weight:
 [0.49428004] [1.8255583] [-2.2803845]
Step:  1100 
Cost:  8.169068 
weight:
 [0.5338884] [1.7907034] [-2.2705908]
Step:  1200 
Cost:  7.8985434 
weight:
 [0.57225895] [1.7569324] [-2.2610528]
Step:  1300 
C

In [54]:
# 방법2

# data
x_data = [[4,4], [8,10], [9,8], [8,5], [8,10], [12,15], [6,8], [10,13], [6,5], [9,12]]
y_data = [[9], [20], [22], [15], [17], [30], [18], [25], [10], [20]]

# placeholder
x = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])

# weight, bias
W = tf.Variable(tf.random_normal([2,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# hypothesis function
y_hat = tf.matmul(x, W) + b

# cost function
cost = tf.reduce_mean(tf.square(y_hat - Y))

# minimization
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-4)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10000):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], feed_dict = {x: x_data, Y: y_data})
    if step % 100 == 0 :
        print("Step: ", step, '\nCost: ', cost_val, '\nweight:\n', W_val, b_val, '\n')
    
    # w1 = 1.402, w2 = 0.808, b = 0.150

Step:  0 
Cost:  1455.0925 
weight:
 [[-0.8271083]
 [-1.0985783]] [-0.03391958] 

Step:  100 
Cost:  6.071838 
weight:
 [[0.9951683]
 [1.00924  ]] [0.17664482] 

Step:  200 
Cost:  3.98563 
weight:
 [[1.0741414]
 [1.0800548]] [0.18560256] 

Step:  300 
Cost:  3.9642296 
weight:
 [[1.0869685]
 [1.0742131]] [0.18688442] 

Step:  400 
Cost:  3.946895 
weight:
 [[1.0969976]
 [1.0657396]] [0.18781616] 

Step:  500 
Cost:  3.9306138 
weight:
 [[1.1066295]
 [1.0574216]] [0.18867636] 

Step:  600 
Cost:  3.915322 
weight:
 [[1.1159645]
 [1.0493563]] [0.18947741] 

Step:  700 
Cost:  3.900959 
weight:
 [[1.1250149]
 [1.0415398]] [0.19022158] 

Step:  800 
Cost:  3.8874657 
weight:
 [[1.1337897]
 [1.0339644]] [0.19091065] 

Step:  900 
Cost:  3.8747902 
weight:
 [[1.1422975]
 [1.0266229]] [0.19154637] 

Step:  1000 
Cost:  3.8628821 
weight:
 [[1.1505464]
 [1.0195079]] [0.19213046] 

Step:  1100 
Cost:  3.851696 
weight:
 [[1.1585447]
 [1.0126123]] [0.19266446] 

Step:  1200 
Cost:  3.8411877 
w